title: Yahya Abou Imran # your name (or website title) here
logo: "/images/profile_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  eXtreme Analyste Programmeur
  <br><br>
  <a href="https://www.linkedin.com/in/alexandre-poitevin-yahya-abou-imran">Profil LinkedIn</a>
  <br><br>
  <a href="https://gitlab.com/yahya-abou-imran">Compte GitLab</a>

theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
