title: Yahya Abou Imran
logo: "/images/profile_image.jpg?raw=true"
description: >
 Extreme Analyst Programeur
 <br><br>
 <a href="https://github.com/yahya-abou-imran">GitHub</a> /
 <a href="https://gitlab.com/yahya-abou-imran">GitLab</a> /
 <a href="https://www.linkedin.com/in/alexandre-poitevin-yahya-abou-imran">LinkedIn</a>
theme: jekyll-theme-minimal
